add checkpoint, metric ..
syncdoth/Eagle-Eye-Pneumonia-Detection pull request #8
Opened 2021-02-28 14:25 UTC by ggoggori

2021-02-28 14:42 UTC, syncdoth requested changes

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +    history = dict(train_acc=[],train_loss=[],val_acc=[],val_loss)
1. val_loss 도 list 로 해주세요
2. 그리고 지금 f1 받아오고 있으니까 val_acc 이 아니라 val_f1 으로 해주세요

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +                    loss,acc = do_train_step(model, optimizer, loss_func, batch, is_train=False)
variable 이름 acc 말고 f1 으로 해주세요. 그리고 변수명 사이에 space 추가해주세요

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +        if val_dataset:
```
if val_dataset:
    # do stuff..
```
보다
```
if val_dataset is None:
    continue
```
가 더 좋습니다. 특히 지금처럼 depth 가 계속 들어가는 경우에는요.

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +        history['val_loss'].append(np.mean(val_loss))
val_dataset 이 없는 경우, `history['val_loss'].append(np.mean(val_loss))` 가 실행되지 않도록 해줘야 할 것 같습니다.

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +
for loop 사이에 스페이스를 추가하지 않는게 python coding convention 입니다.

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +    f1_socre = f1_score(batch["targets"], predicted, average='weighted')
weighted 말고 'macro' 혹은 'micro' 로 부탁드립니다.

2021-02-28 14:42 UTC, syncdoth commented on models/train.py
> +def save_checkpoint(epoch,model,optimizer,filename):
function parameter 사이에 스페이스 추가해주세요.

2021-02-28 14:44 UTC, ggoggori commented on models/train.py
> +    history = dict(train_acc=[],train_loss=[],val_acc=[],val_loss)
넵 피드백 감사합니닷! 👍

2021-03-01 06:11 UTC, syncdoth approved these changes

2021-03-01 06:11 UTC, merged