type_classifier upload
syncdoth/Eagle-Eye-Pneumonia-Detection pull request #9
Opened 2021-03-01 13:35 UTC by leonilpark

2021-03-01 14:29 UTC, syncdoth commented
ipynb 말고 py 파일로 부탁드립니다.

2021-03-01 14:49 UTC, leonilpark commented
바로 수정하겠습니다!

2021-03-01 17:16 UTC, syncdoth requested changes
EfficientNet 구현과 TypeClassifier 클래스를 분리했으면 좋겠습니다. TypeClassifer 는 하나의 Wrapper Class 같은 느낌이고, 그 세부 구현은 다양한 버전으로 선택할 수 있도록이요. 즉, 이전에 올리셧던 EfficientNet.ipynb 파일을 .py 버전으로 올려주시고, type_classifier.py 에서는 EfficientNet.py 에서 구현을 import 해와서 사용하는 식으로요.

그리고 이건 급한건 아니고 나중에 작업해도 되는 일이지만 궁극적으로는 장훈님이 구현하신 EfficientNet 과 `EfficientNet-Pytorch` 구현 중에 선택할 수 있으면 좋을 것 같습니다. `__init__()` 안에 parameter 로 받아서요.

2021-03-01 17:16 UTC, syncdoth commented on models/type_classifier.py
> +                    InvertedResidualBlock(
`CNNBlock`, `InvertedResidualBlock` 의 구현이 없습니다.

2021-03-01 17:16 UTC, syncdoth commented on models/type_classifier.py
> +        super(EfficientNet, self).__init__()
`EfficientNet` 이 아니라 `TypeClassifier` 가 들어가야합니당.

2021-03-01 17:17 UTC, syncdoth commented on models/type_classifier.py
> +        super(EfficientNet, self).__init__()
그리고 사실 python version 3 부터는 이런식으로 할 필요 없이 `super().__init__()` 만 하셔도 됩니다.

2021-03-09 08:58 UTC, syncdoth commented
늦어지고 있어서 일단 넣도록 하겠습니다.

2021-03-09 08:58 UTC, merged